- hosts: test_servers
  become: yes
  tasks:
     - name: get JDK tarball (as RPM file)
       get_url:
         url:     "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"
         headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
         dest:    "/home/opc"
